version: '2'
services:
    auth:
        image: f-auth:latest
        container_name: auth
        restart: always
        ports:
            - "8070:8070"
        env_file:
            - env
        networks:
            des:
                ipv4_address: 10.20.1.20
        dns_search: .
    #postgresql:
     #   image: postgres:9.6.5
      #  container_name: des-db
       # restart: always
        #volumes:
         #   - ~/opt/des/postgresql/:/var/lib/postgresql/data/:z
          #  - ./des_db_structure.sql:/docker-entrypoint-initdb.d/des_db_structure.sql
        #networks:
         #   des:
          #      ipv4_address: 10.20.1.10
        #dns_search: .
networks:
    des:
        ipam:
            driver: default
            config:
                - subnet: 10.20.0.0/16
